// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meniyxsbtuwebchjtnjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lbml5eHNidHV3ZWJjaGp0bmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMzA5MzgsImV4cCI6MjA0OTcwNjkzOH0.CDjc7HLKc9-lwoyC4sdvQnp1qPsrzqDiVjrIcu4Nx00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);